print ("what is your name?")
name = input()
print ("how old are you?")
Age = int (input())
print ("how tall are you?")
height= float (input())
print ("how much do you weigh?")
weight = float (input())
BMI = weight/(height*height)
print ()
print (name + " you are " + str (Age) + " years old and your bmi is " + str (BMI))